builds:
  - binary: yt2abs
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: yt2abs
    homepage: "https://github.com/simonwehle/yt2abs"
    repository:
      owner: simonwehle
      name: homebrew-tools

checksum:
  name_template: 'checksums.txt'